In [1]:
# 모듈을 import 합니다.
# 타인이 만들어 놓은 라이브러리를 import 하면 본인의 코드에서 해당 코드들을 쉽게 사용할 수 있습니다.
import numpy as np ## numpy라는 모듈을 np라는 이름으로 모듈 전체를 import합니다.
from sklearn.linear_model import LinearRegression # sklearn에 있는 linear_model 에서 LinearRegression이라는 sub class만 import 합니다.

In [2]:
X = np.array([[1,1],[1,2],[2,2],[2,3],[3,3]]) # 주석을 쓰세요

In [3]:
y = np.dot(X, np.array([1,2]))+3 # 정답인 y의 값들을 np.dot(내적) 함수를 이용하여 만듭니다.

In [4]:
y

array([ 6,  8,  9, 11, 12])

### y = 1\*x0 + 2\*x1 +3 우리가 만들 회귀선은 이런 방정식을 따릅니다.

### y = w0\*x0 + w1\*x1 + b 이 모델은 w0, w1, b를 맞추는 것을 목표로 학습하게 됩니다.

In [5]:
reg = LinearRegression().fit(X,y)

In [6]:
print(reg)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)


In [7]:
# R^2 score 모델의 평가 방법 중 하나
reg.score(X,y)

1.0

In [8]:
#w0,w1의 계수
reg.coef_

array([1., 2.])

In [9]:
# 독립항 b
reg.intercept_

3.000000000000001

In [10]:
reg.predict(np.array([[6,6]]))

array([21.])

### ------------------------------------------------------------------------------------------

In [11]:
test_x = np.array([[1,1,1],[1,2,3],[4,5,7],[0,1,2]])

In [12]:
test_y = np.array([ 4,  7, 29, -1])

In [13]:
test_y

array([ 4,  7, 29, -1])

### test_X와 test_y의 회귀선을 찾으세요